Feature/api
Hitin/task_manager pull request #20
Opened 2019-12-18 09:30 UTC by Hitin

2019-12-24 09:24 UTC, Andrew8xx8 requested changes

2019-12-24 09:24 UTC, Andrew8xx8 commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :html, :json
Почему API отвечает на `html`? в API возвращаться только структурированные данные должны

2019-12-24 09:24 UTC, Andrew8xx8 commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :html, :json
Это справедилово для всего API, почему эта конфигурация задана только для API tasks?

2019-12-24 09:24 UTC, Andrew8xx8 commented on app/controllers/api/v1/tasks_controller.rb
> +        render(json: { errors: task.errors }, status: :unprocessable_entity)
Будет ли это работать как ожидается? В случае неудачного дестроя ошибки будут сложены в task.errors?

2019-12-24 09:24 UTC, Andrew8xx8 commented on app/serializers/task_serializer.rb
> +  def id
Зачем преобразовывать в строку? Данные из API всегда должны возвращаться тем типом который есть. id — число, вот и возвращаться должно число, а не строка

2019-12-24 11:55 UTC, Hitin commented on app/serializers/task_serializer.rb
> +  def id
Подскажи, это сделано специально чтобы понимать разницу?
https://fullstack-learning.firebaseapp.com/lessons/7/practice/5
Я наоброт подумал что нужно все приводить к формату строки.
Но спасибо, учту в дальнейшем.

2019-12-24 12:14 UTC, Hitin commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :html, :json
Понял ошибку, поправил.

2019-12-24 12:25 UTC, Hitin commented on app/controllers/api/v1/tasks_controller.rb
> +        render(json: { errors: task.errors }, status: :unprocessable_entity)
Если я тебя правильно понял, сюда складывать нужно не весь массив с ошибками а только сообщения?

2019-12-26 13:23 UTC, artempartos approved these changes

2019-12-26 13:23 UTC, artempartos commented on test/factories/tasks.rb
> +    author_id { create :user }
не надо так писать, надо создать трейт

2019-12-27 06:37 UTC, closed without merging