Feature/generate models
Hitin/task_manager pull request #5
Opened 2019-11-22 07:07 UTC by Hitin

Изначально, создал ветку без гемов factory bot до принятия PR. Сгенерировал все необходимые модели и мигрировал их в таблицу. После принятия моего PR создал отдельную ветку в которой уже создавал модели с гемом factory bot. Затем сделал ребэйз.

2019-11-22 09:00 UTC, artempartos requested changes

2019-11-22 09:00 UTC, artempartos commented on test/factories/tasks.rb
> +    name { "MyString" }
вынеси все в sequences. здесь обычно не надо описывать каждое поле, ассациации оставь пустыми по умолчанию

2019-11-22 09:00 UTC, artempartos commented on test/fixtures/developers.yml
> +#
удали фикстуры, мы их не используем

2019-11-22 09:00 UTC, artempartos commented on test/models/developer_test.rb
> +  # test "the truth" do
удали неиспользуемые тесты

2019-11-25 07:07 UTC, Hitin commented on test/factories/tasks.rb
> +    user
Здесь должна быть ассоциация author?, т.к. мы же поле в задаче проверяем.
Или мы все таки ссылаемся на factory с которой хотим связать?

2019-11-25 07:13 UTC, Hitin commented on test/factories/users.rb
> +    task
Здесь наверно связь с задачей не нужна, т.к. на моменте создания у нас задач не может быть. Правильно?

2019-11-28 11:18 UTC, artempartos requested changes

2019-11-28 11:18 UTC, artempartos commented on test/factories/tasks.rb
> +    sequence(:name) { |n| "name#{n}" }
правилььно будет здесь оставиттьт простот name
а в файл sequenced описать как создаватть name

2019-11-28 11:19 UTC, artempartos requested changes

2019-11-28 11:19 UTC, artempartos commented on test/factories/tasks.rb
> +    assignee
assignee { nil }
по умолчанию лучше не предсоздавать связи

2019-11-30 20:17 UTC, artempartos requested changes

2019-11-30 20:17 UTC, artempartos commented on test/factories/tasks.rb
> +    name
тут правильно, ниже сделай также для description

2019-11-30 20:17 UTC, artempartos commented on test/factories/users.rb
> +    first_name { generate :string }
тут тоже в sequences

2019-12-01 10:01 UTC, Hitin commented on test/factories/sequences.rb
> +  end
Чтобы не писать каждую sequence в отдельности можно написать так?
sequence(:string, aliases: [:desciption, :first_name, :last_name, :password]) { |n| "string#{n}" }

2019-12-01 12:59 UTC, artempartos approved these changes

2019-12-01 12:59 UTC, artempartos commented on test/factories/sequences.rb
> +  end
можно

2019-12-01 12:59 UTC, artempartos commented
👍

2019-12-02 05:29 UTC, closed without merging